### ISSUE TITLE
Training with sparse features

### ISSUE THREAD

**Issue by allenschmaltz** [grammatical/baselines-emnlp2016#3]
**For training sparse features (as with `train/config.sparse.yml)`:**

`Line 293` of `train/run_cross.perl`:

The following file does not exist: `$DIR/cross.00/work.err-cor/binmodel.err-cor/moses.mert.ini.sparse`

In `train/train_smt.perl`:

For the `esm` flag:

`$MOSESDIR/bin/ESMSequences` (on `line 288`) does not appear to be available in a standard
Moses build. Do you plan to make it available?

**Comment by emjotde** [comment]
Hi,
the ESM was never used in our model. That was an experiment of mine that was supposed to mimic the OSM but based on LCS edits instead of word alignments. You want the OSM which should work with the current scripts. We should remove the `esm` flag to avoid confusion.

**Comment by allenschmaltz** [comment]
Thanks for the clarification.
