### ISSUE TITLE
Cannot download the language models following the links in README

### ISSUE THREAD

**Issue by karendeng** [grammatical/baselines-emnlp2016#4]
Sorry for that I cannot download the language models following the links in README:

Wikipedia language model (22G)
http://odkrywka.wmi.amu.edu.pl/static/data/baselines-emnlp2016/wikilm.tgz

Common Crawl language model (26G)
http://odkrywka.wmi.amu.edu.pl/static/data/baselines-emnlp2016/cclm.tgz

The error was "File not found"

Could you kindly update the download links to LMs?

**Comment by snukky** [comment]
This has been fixed few months ago.
