### ISSUE TITLE
can not find the Lang-8 NAIST corpus

### ISSUE THREAD

**Issue by ghozn** [grammatical/baselines-emnlp2016#9]
Hi,
I can't download the Lang-8 NAIST corpus using these two links:
http://cl.naist.jp/nldata/lang-8/
http://odkrywka.wmi.amu.edu.pl/static/data/baselines-emnlp2016/lang8.tgz

How can I download it?

**Comment by snukky** [comment]
I've updated the links:
- https://sites.google.com/site/naistlang8corpora/
- http://data.statmt.org/romang/gec-emnlp16/lang8.tgz

**Comment by ghozn** [comment]
Thank you very much.
